# Word Embedding
Word embeddings provide a dense representation of words and their relative meanings.They are an improvement over sparse representations used in simpler bag of word model representations.Word embeddings can be learned from text data and reused among projects. They can also be learned as part of fitting a neural network on text data.



In [1]:
#Importing Necessary Libraries for Tensorflow Hub
import numpy as np
import tensorflow_hub as hub

In [2]:
#Loading the Dataset
embedding= hub.load ("https://tfhub.dev/google/Wiki-words-250/2")

In [3]:
a = embedding ([" king "])
b = embedding ([" man "])
c = embedding ([" woman "])
d = embedding ([" queen "])

In [4]:
# Storing the result ofvector(King) − vector(Man) + vector(Woman)
X= a-b+c
print("King-Man+Woman:", [X])

King-Man+Woman: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[-0.12994584, -0.17411731,  0.08241335, -0.09460426, -0.02963368,
         0.00833852, -0.01580581, -0.07200217, -0.0374763 , -0.01857486,
         0.04575163, -0.06350955,  0.0310036 ,  0.04439414,  0.06356907,
        -0.02856771,  0.05558529,  0.07249814, -0.02398837,  0.0455301 ,
        -0.07038731,  0.00989324, -0.05211002, -0.02339969, -0.10386609,
        -0.00747646, -0.0174827 , -0.15109651, -0.16803886, -0.03159868,
        -0.04374632,  0.0941674 ,  0.05635576, -0.11544351, -0.01706913,
        -0.0181496 ,  0.05560432,  0.01284544, -0.09410097,  0.08030569,
        -0.13458134, -0.12798919, -0.14993384,  0.06665589,  0.07577673,
        -0.12577374, -0.06869593, -0.10468247, -0.01054525, -0.07139292,
        -0.00569897, -0.02220746, -0.11851092, -0.09434773,  0.06391967,
         0.04567089,  0.14339279, -0.13938236, -0.03750862,  0.03229091,
         0.07670465,  0.05507568, -0.01978571,  0.0488369

Finding Other Unique Similarities between Vector Representation of words like King, Man, Woman and Queen.

In [5]:
# Storing the result ofvector(Woman) − vector(King) + vector(Queen) to find similarity of Man
Y= c-a+d
print("Woman-King+Queen:", [Y])

Woman-King+Queen: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[ 0.02118351, -0.12248733, -0.06041376,  0.07144362, -0.10978897,
         0.07119545,  0.04992773, -0.02743515, -0.06480911, -0.20285434,
         0.11473861,  0.02721604,  0.05260982,  0.1065385 ,  0.01394302,
        -0.1647489 ,  0.07203833,  0.11857994, -0.00095271, -0.09147857,
         0.03879085,  0.02359177,  0.04185368, -0.04939352, -0.07421876,
         0.03422938,  0.08419857,  0.09070219,  0.00358181,  0.1773604 ,
         0.1088568 ,  0.08282477,  0.12156986, -0.1598848 , -0.05240928,
        -0.13726465,  0.0233911 ,  0.00856919,  0.09519659, -0.03324209,
        -0.02363841, -0.17106755, -0.08100536, -0.05365514,  0.08478432,
        -0.0671075 , -0.1854074 ,  0.07032573, -0.07756672, -0.08777828,
         0.08333436,  0.0141644 , -0.09988222,  0.08947498,  0.01964116,
         0.01092771,  0.01083473, -0.01248896,  0.08680015,  0.01968326,
        -0.10005222, -0.08237934, -0.13430107,  0.08316

In [16]:
# Storing the result of queen - woman + man to find similairy with vector King.
T=d-c+a
print("Queen-Woman+King:", [T])

Queen-Woman+King: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[-1.58536479e-01, -1.61520213e-01,  1.17736332e-01,
        -1.74841017e-01,  2.41178013e-02, -1.76977366e-03,
        -3.86548638e-02, -1.25231683e-01, -3.00807562e-02,
         1.83633715e-01, -5.97624853e-03, -6.47249743e-02,
         3.93698700e-02,  1.15037151e-01,  1.09701708e-01,
         2.17840113e-02,  1.05455451e-01,  3.75334639e-03,
        -9.28346440e-02,  1.98147416e-01,  1.67360064e-02,
        -2.71459669e-02, -4.83037569e-02, -2.35077310e-02,
        -1.40331686e-04,  2.93595977e-02, -5.78160211e-02,
        -1.37882560e-01, -2.22912565e-01, -9.74679440e-02,
         1.31877568e-02,  1.89134181e-02,  8.54464471e-02,
        -8.20023566e-02,  1.37376226e-02,  6.24712855e-02,
        -9.72158462e-03,  4.50491682e-02, -1.03875771e-01,
         9.19655412e-02, -1.22242302e-01, -2.65491158e-02,
        -2.38390028e-01,  8.49930719e-02,  1.30566627e-01,
        -9.99232978e-02, -8.80194977e-02, -1.3

In [19]:
#Queen-Woman+Man to find similarity with King
P=d-c+b
print("Queen-Woman+Man:", [P])

Queen-Woman+Man: [<tf.Tensor: shape=(1, 250), dtype=float32, numpy=
array([[-0.07304484, -0.10473301,  0.02056202, -0.06359452, -0.04180158,
         0.07061455, -0.01422972, -0.07333106,  0.00619363,  0.0811443 ,
        -0.00183138,  0.02562532,  0.06503096,  0.14791726,  0.02977548,
        -0.06340177,  0.09105583,  0.0010729 , -0.07499544,  0.11528815,
         0.0935578 , -0.03184626,  0.00408047, -0.04401265,  0.02318001,
         0.04371331,  0.03528067,  0.02045511, -0.08324654,  0.0530984 ,
         0.07559922, -0.01135975,  0.10390387, -0.07372636, -0.04578836,
         0.01495593, -0.04728576,  0.05573048,  0.01287029,  0.01603144,
        -0.01436903, -0.05028018, -0.12826449,  0.03077834,  0.13549316,
        -0.02707155, -0.14796142, -0.01444141, -0.03875586,  0.01317856,
        -0.05911564,  0.06295926, -0.02640765,  0.00639696, -0.0384201 ,
        -0.06233981,  0.06564523, -0.20331535,  0.06032293,  0.0895168 ,
        -0.02003701,  0.06907512, -0.03137987,  0.024022

In [20]:
# Storing the result ofvector(King) − vector(Man) to find similarity with vector(Queen) − vector(Woman)
Z= a-b #King-Man
U= d-c #Queen-Woman

In [21]:
#Calculating the Cosine Similarity between Vectors of Words.
from sklearn.metrics.pairwise import cosine_similarity

print("Similarity between King-Man+Woman and Queen:",cosine_similarity(X,d))
print("Similarity between Woman-King+Queen and Man:",cosine_similarity(Y,b))
print("Similarity between King-Man and Queen-Woman:",cosine_similarity(Z,U))
print("Similarity between Queen-Woman+King and Man:",cosine_similarity(T,b))
print("Similarity between Queen-Woman+Man and King:",cosine_similarity(P,a))

print("Similarity between Man and Woman:",cosine_similarity(b,c))
print("Similarity between King and Queen:",cosine_similarity(a,d))
print("Similarity between Man and King:",cosine_similarity(a,b))
print("Similarity between Woman and Queen:",cosine_similarity(c,d))
print("Similarity between Man and Queen:",cosine_similarity(b,d))


Similarity between King-Man+Woman and Queen: [[0.763873]]
Similarity between Woman-King+Queen and Man: [[0.6374301]]
Similarity between King-Man and Queen-Woman: [[0.7635017]]
Similarity between Queen-Woman+King and Man: [[-0.01385604]]
Similarity between Queen-Woman+Man and King: [[0.7397525]]
Similarity between Man and Woman: [[0.83813375]]
Similarity between King and Queen: [[0.71021986]]
Similarity between Man and King: [[0.3612764]]
Similarity between Woman and Queen: [[0.5902161]]
Similarity between Man and Queen: [[0.45445222]]


 To Find the top 5 closest words to the word "dog"

In [10]:
# Creating my own small corpus of words related to dog
dog_corpus = ['pup', 'canine', 'doggo', 'pet', 'hound', 'puppy', 'sheep dog', 'bull dog', 'pet dog', 'cat','wolf']

In [11]:
# Embedding all the words in the list from dog corpus
embed_dog = []
for i in range(len(dog_corpus)):
  embed_dog.append(embedding([dog_corpus[i]]))

In [12]:
e=embedding(['dog'])

In [13]:
#For Storing the Cosine Similarity of words
cos_sim = {}
for i in range(len(embed_dog)):
  cos_sim[dog_corpus[i]] = cosine_similarity(e,embed_dog[i])

In [23]:
# For Creating Asceding order of Cosine Similarity
cos_sim_asc = {}
sorted_values = sorted(cos_sim.values())
for i in sorted_values:
    for k in cos_sim.keys():
        if cos_sim[k] == i:
            cos_sim_asc[k] = cos_sim[k]
            break

In [24]:
# Top 5 words similar to dog
size = len(list(cos_sim_asc))
print(size)
top5 = list(cos_sim_asc.keys())
for i in range(size):
  if i<(size-5):
    continue
  else:
    print("Word :", top5[i])
    print("Cosine Similarity :", cos_sim_asc[top5[i]])

11
Word : puppy
Cosine Similarity : [[0.8488173]]
Word : cat
Cosine Similarity : [[0.8490829]]
Word : bull dog
Cosine Similarity : [[0.86425537]]
Word : sheep dog
Cosine Similarity : [[0.88398373]]
Word : pet dog
Cosine Similarity : [[0.95539427]]
